### ISSUE TITLE
Issue with section title on the Home page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#893] opened 2022-11-18 17:52 UTC
The app on `main` has a layout issue on the home page:

![image](https://user-images.githubusercontent.com/3056480/202770140-0d25ce8e-0df4-46f1-b481-ffb268260fb5.png)

**Comment by vpchung** [comment] 2022-11-18 18:42
I suspect it has to do with conflicting CSS namespace and definitions - I'll take a look.

**Comment by vpchung** [comment] 2022-11-18 18:51
@tschaffter which browser are you using?  I am on the latest Chrome and cannot reproduce what you are seeing (while in `main`):

![Screen Shot 2022-11-18 at 10 50 25 AM](https://user-images.githubusercontent.com/9377970/202780679-670e27c8-fba4-45d8-a203-144c3ae77b0b.png)

**Comment by vpchung** [comment] 2022-11-18 18:53
I also tried checking out my latest feature branch (`search-page`) and cannot reproduce the issue.

**Comment by vpchung** [comment] 2022-11-18 18:54
@tschaffter ah, figured it out!  I will have a fix implemented shortly.

**Comment by vpchung** [comment] 2022-11-18 21:21
Thanks for identifying the issue, @tschaffter !  I pushed a fix with #897.

**Comment by tschaffter** [comment] 2022-11-19 00:41
> which browser are you using?

FF

**Closed** 2022-11-19 00:42 UTC
Labels: bug, frontend
